dependencies:
  - pip:
      - mailersend==0.5.8
      - msgraph-sdk==1.21.0
      - ydata-profiling==4.12.0
      - semantic-link-labs==0.8.6
      - deep-translator==1.11.4
      - googletrans==4.0.2
      - gitpython==3.1.43
      - dbt-fabric==1.8.8
      - msal==1.31.1
